name: partner
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  date_picker_timeline: ^1.2.5
  intl: ^0.19.0
  device_preview: ^1.2.0
  get: ^4.7.2
  image_picker: ^1.1.2
  flutter_map: ^8.1.1
  location: ^8.0.0
  latlong2: ^0.9.1
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.1
  http: ^1.3.0
  geocoding: ^3.0.0
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  
  assets:   
      - assets/icon/info_icon.png   
      - assets/icon/car_icon.png     
                 
